### ISSUE TITLE
torch.FloatTensor type error

### ISSUE THREAD

**Issue by cloudliu01** [ayooshkathuria/YOLO_v3_tutorial_from_scratch#10]
Without any changes on the code downloaded, when I ran command 'python detect.py --images imgs --det det', I got errors below:

> Loading network.....
Network successfully loaded

> 256.4507   62.3959  374.7849  120.3694    0.9988    0.9377    7.0000
 265.0707   62.5722  379.6248  121.3135    0.9726    0.8795    7.0000
 254.2707   69.4995  376.2362  125.0286    0.9040    0.9200    7.0000
  58.2381   80.8954  312.3383  296.0082    0.9004    0.9983    1.0000
  61.3210   58.3361  311.3177  316.3376    0.8639    0.9972    1.0000
  89.2337   73.0579  308.4990  302.5144    0.9240    0.9960    1.0000
  63.8950   89.8635  308.2446  312.9947    0.9908    0.9991    1.0000
  54.9051   76.0959  312.2937  337.0284    0.9859    0.9981    1.0000
  87.4243   84.2302  307.2956  313.9760    0.9861    0.9996    1.0000
  66.4022   72.3304  323.7131  332.9052    0.5739    0.9988    1.0000
  59.7964  112.0306  173.2647  379.6315    0.9257    0.9818   16.0000
  66.6987  160.9137  173.3377  393.2019    0.9999    0.9980   16.0000
  73.8193  154.1310  187.0550  391.4006    0.9704    0.9931   16.0000
  63.6121  176.9761  171.9654  404.1670    0.9892    0.9789   16.0000
[torch.cuda.FloatTensor of size 14x7 (GPU 0)]

>Traceback (most recent call last):
  File "detect.py", line 126, in <module>
    prediction = write_results(prediction, confidence, num_classes, nms_conf = nms_thesh)
  File "/media/lliu/hdd4/YOLO_v3_tutorial_from_scratch/YOLO_v3_tutorial_from_scratch-master/util.py", line 159, in write_results
    ious = bbox_iou(image_pred_class[i].unsqueeze(0), image_pred_class[i+1:])
  File "/media/lliu/hdd4/YOLO_v3_tutorial_from_scratch/YOLO_v3_tutorial_from_scratch-master/util.py", line 43, in bbox_iou
    iou = inter_area / (b1_area + b2_area - inter_area)
  File "/home/lliu/.conda/envs/pyTorch_35_new/lib/python3.5/site-packages/torch/tensor.py", line 300, in __sub__
    return self.sub(other)
TypeError: sub received an invalid combination of arguments - got (torch.FloatTensor), but expected one of:
> * (float value)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
> * (torch.cuda.FloatTensor other)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
> * (float value, torch.cuda.FloatTensor other)

After tracing it back I found it's an bug in line 37, util.py: All the variables before this line are in **(GPU 0)**, whereas the output **inter_area** of this line doesn't contain **(GPU 0)**, which causes the subsequent **iou** calculation failed (line 43).

The data inspection of **inter_rect_x2**, note the **(GPU 0)**:
>In [5]: inter_rect_x2
Out[5]: 

> 307.2956
 308.2446
 308.2446
 308.2446
 308.2446
 308.2446
[torch.cuda.FloatTensor of size 6 (GPU 0)]

The data inspection of **inter_area** :
> In [4]: inter_area
Out[4]: 

> 49504.1289
 54990.4844
 47005.5273
 50822.8750
 54990.4844
 54428.5430
[torch.FloatTensor of size 6]

To fix the issue, I just simply added the .cuda() function to the np commands in line 37:
> inter_area = np.maximum(inter_rect_x2 - inter_rect_x1 + 1, 0).cuda()*np.maximum(inter_rect_y2 - inter_rect_y1 + 1, 0).cuda()

This seems working to me; however, I don't know why just me saw this issue. Wrote this down for others reference.

BTW, I am using Pytorch 0.3, cuda 8 and cudnn 6

**Comment by ayooshkathuria** [comment]
Okay, there was a bug in NMS which caused to give  > 0 IOU threshhold for two boxes that didn't overlap. I pushed it just yesterday, but couldn't check it on GPU as I don't have access to one on weekdays. It works fine on CPU. 

Your solution would then break the code on CPU, since .cuda() will raise an error. The best way to go about it would be to use `torch.maximum` or something. I'll look into it in a couple of hours and push the changes. Thanks for pointing out the bug though. If you could verify it with torch.max, perhaps you could make a pull request too. It'll be a few hours before I can push the fix.

**Comment by ayooshkathuria** [comment]
I've fixed the issue. It works fine on GPU now.

**Comment by e-sha** [comment]
> if torch.cuda.is_available():
>             inter_area = torch.max(inter_rect_x2 - inter_rect_x1 + 1,torch.zeros(inter_rect_x2.shape).cuda())*torch.max(inter_rect_y2 - inter_rect_y1 + 1, torch.zeros(inter_rect_x2.shape).cuda())
>     else:
>             inter_area = torch.max(inter_rect_x2 - inter_rect_x1 + 1,torch.zeros(inter_rect_x2.shape))*torch.max(inter_rect_y2 - inter_rect_y1 + 1, torch.zeros(inter_rect_x2.shape))

It's better to use torch.clamp, so you don't actually need memory allocation for tensor of zeros:
`nter_area =  torch.clamp(inter_rect_x2 - inter_rect_x1 + 1,min=0)*torch.clamp(inter_rect_y2 - inter_rect_y1 + 1, 0)`

**Comment by ayooshkathuria** [comment]
Can you make a pull request? I'm. A bit busy with college stuff that I can't access my work PC right now. I made the above pushes directly from the website. I agree with the choice of ,`torch.clamp` ( I have used the function to clip bounding boxes that exceed dimensions of the image). Plus. If you are gonna do the PR, please make sure the code works both on CUDA and CPU. I guess clamp is device agnostic but I can't exactly nail it down. Thanks for the suggestion.
