### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by FishYuLi** [ayooshkathuria/YOLO_v3_tutorial_from_scratch#2]
Hi,
This is a great work! 
I wondered if this implementation can reproduce 33% mAP on COCO as stated in YOLO_v3 paper?
I think it will be great to list current performance of this code in README.md.

Thanks a lot!

**Comment by ayooshkathuria** [comment]
Yet to implement the code that calculates the COCO metric. Busy with writing my undergraduate thesis to be presented this May. Will do for sure once the code is ready. Thanks for the suggestion about adding it in the README.
