### ISSUE TITLE
ISSUE:'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by MidiyaZhu** [ayooshkathuria/YOLO_v3_tutorial_from_scratch#37]
When I ran the detect.py, the error issued as    
`    img_w, img_h = img.shape[1], img.shape[0]

AttributeError: 'NoneType' object has no attribute 'shape'`  in util.py
I think it might be the question of loading img, but when I debug darknet.py, I could get the result of img.

Anyone could help me solve the problem? Thanks a lot.

**Comment by anjanaouseph** [comment]
Hi @MidiyaZhu Can u help me with it? I have encountered the same issue.
